# Exercise 1: List Comprehension with Function Calls

## Context

You are analyzing a portfolio of stocks and need to calculate various metrics efficiently using list comprehensions.

## Task 1: Calculate Compound Annual Growth Rate (CAGR)

Given a list of dictionaries containing stock data, calculate the CAGR for each stock using a list comprehension.

Formula: CAGR = (final_value / initial_value)^(1/years) - 1

In [9]:
portfolio = [
    {"ticker": "AAPL", "initial_price": 100, "final_price": 180, "years": 5},
    {"ticker": "MSFT", "initial_price": 50, "final_price": 120, "years": 4},
    {"ticker": "GOOGL", "initial_price": 800, "final_price": 1500, "years": 6},
    {"ticker": "AMZN", "initial_price": 300, "final_price": 450, "years": 3},
    {"ticker": "TSLA", "initial_price": 200, "final_price": 250, "years": 2}
]

def calc_cagr(initial_price: int, final_price: int, years: int) -> float:

    return (final_price / initial_price) ** (1 / years) - 1


# TODO: Use list comprehension to create a list of dictionaries with ticker and cagr
cagr_results = [dict(ticker=stock["ticker"], cagr= calc_cagr(stock["initial_price"], stock["final_price"], stock["years"])) for stock in portfolio]

print("Stock CAGR Analysis:")
for stock in cagr_results:
    # print(f"{stock['ticker']}: {stock['cagr']:.2%}")
    print(stock)

Stock CAGR Analysis:
{'ticker': 'AAPL', 'cagr': 0.12474611314209483}
{'ticker': 'MSFT', 'cagr': 0.24466595457695672}
{'ticker': 'GOOGL', 'cagr': 0.1104530774261625}
{'ticker': 'AMZN', 'cagr': 0.14471424255333187}
{'ticker': 'TSLA', 'cagr': 0.1180339887498949}


## Task 2: Filter and Transform

Using the same portfolio data, create a list comprehension that:
1. Only includes stocks with CAGR > 10%
2. Returns dictionaries with ticker, cagr, and rating where rating is:
   - "Excellent" if CAGR > 20%
   - "Good" if CAGR > 10%
## Expected Output
```
Stock CAGR Analysis:
AAPL: 12.47%
MSFT: 24.57%
GOOGL: 11.05%
AMZN: 14.47%
TSLA: 11.80%

Top Performing Stocks:
AAPL: 12.47% - Good
MSFT: 24.57% - Excellent
GOOGL: 11.05% - Good
AMZN: 14.47% - Good
TSLA: 11.80% - Good
```

In [19]:
# cagr_results 

def get_rating(cagr):
    """
    Assign a rating based on CAGR
    
    Parameters:
    - cagr: Compound Annual Growth Rate as decimal
    
    Returns:
    - Rating string
    """
    if cagr > 0.2:
        return "Excellent"
    elif cagr > 0.1:
        return "Good"
    else:
        return "Poor"
    
# TODO: Create list comprehension with filter and rating
top_performers = [{"ticker":p["ticker"],"cagr":p["cagr"],"rating":get_rating(p["cagr"])} for p in cagr_results if p["cagr"] > 0.10]
print("\nTop Performing Stocks:")
for stock in top_performers:
    print(f"{stock['ticker']}: {stock['cagr']:.2%} - {stock['rating']}")


Top Performing Stocks:
AAPL: 12.47% - Good
MSFT: 24.47% - Excellent
GOOGL: 11.05% - Good
AMZN: 14.47% - Good
TSLA: 11.80% - Good


# Exercise 2: Portfolio Analysis Functions

## Objective
Build a modular portfolio analysis system using functions that call other functions. You will work with a dictionary containing portfolio data and create functions to analyze and format the results.

## Provided Data Structure

We provide you with the following portfolio dictionary:
```python
portfolio = {
    'AAPL': {'shares': 50, 'purchase_price': 150.00, 'current_price': 178.50},
    'MSFT': {'shares': 30, 'purchase_price': 280.00, 'current_price': 310.25},
    'GOOGL': {'shares': 20, 'purchase_price': 2800.00, 'current_price': 2650.75},
    'TSLA': {'shares': 15, 'purchase_price': 700.00, 'current_price': 245.30}
}
```

Each stock entry contains:
- `shares`: Number of shares owned
- `purchase_price`: Price per share when purchased
- `current_price`: Current market price per share

## Tasks

### Task 1: Basic Calculation Functions

Implement the following functions:

**a) `calculate_position_value(shares, current_price)`**
- Parameters: number of shares (int/float), current price per share (float)
- Returns: total current value of the position (float)

**b) `calculate_position_cost(shares, purchase_price)`**
- Parameters: number of shares (int/float), purchase price per share (float)
- Returns: total cost basis of the position (float)

**c) `calculate_position_gain_loss(shares, purchase_price, current_price)`**
- Parameters: number of shares, purchase price, current price
- Returns: absolute gain/loss in dollars (float)
- Hint: This function should call the two functions above

**d) `calculate_position_return(shares, purchase_price, current_price)`**
- Parameters: number of shares, purchase price, current price
- Returns: percentage return (float)
- Hint: Use the gain/loss function and cost function

In [45]:
def calculate_position_value(shares: float, current_price: float) -> float:
    return shares * current_price

def calculate_position_cost(shares: float, purchase_price: float) -> float:
    return shares * purchase_price

def calculate_position_gain_loss(shares: float, purchase_price: float, current_price: float) -> float:
    return calculate_position_value(shares, current_price) - calculate_position_cost(shares, purchase_price)

def calculate_position_return(shares: float, purchase_price: float, current_price: float) -> float:
    gain_loss = calculate_position_gain_loss(shares, purchase_price, current_price)
    cost = calculate_position_cost(shares, purchase_price)
    return (gain_loss / cost) * 100 if cost != 0 else 0

calculate_position_return(50, 150, 220)

46.666666666666664

### Task 2: Portfolio Analysis Function

**` def analyze_portfolio(portfolio)`**
- Parameter: portfolio dictionary (as provided above)
- Returns: dictionary with the following structure:
```python
{
    'total_invested': float,      # Total amount invested across all positions
    'total_current_value': float, # Current total value of portfolio
    'total_gain_loss': float,     # Total gain/loss in dollars
    'total_return': float,        # Overall portfolio return in %
    'positions': {
        'AAPL': {
            'current_value': float,
            'gain_loss': float,
            'return_pct': float
        },
        # ... same for other stocks
    }
}
```

This function must call your calculation functions from Task 1.

In [44]:
portfolio = {
    'AAPL': {'shares': 50, 'purchase_price': 150.00, 'current_price': 178.50},
    'MSFT': {'shares': 30, 'purchase_price': 280.00, 'current_price': 310.25},
    'GOOGL': {'shares': 20, 'purchase_price': 2800.00, 'current_price': 2650.75},
    'TSLA': {'shares': 15, 'purchase_price': 700.00, 'current_price': 245.30}
}

In [67]:
def analyze_portfolio(portfolio: dict) -> dict:
    total_invested = 0
    total_current_value = 0

    for ticker, data in portfolio.items():
        total_invested += calculate_position_cost(data["shares"], data["purchase_price"])
        total_current_value += calculate_position_value(data["shares"], data["current_price"])

    total_gain_loss = total_current_value - total_invested
    total_return = (total_gain_loss / total_invested) * 100

    return {
        'total_invested': total_invested,      # Total amount invested across all positions
        'total_current_value': total_current_value, # Current total value of portfolio
        'total_gain_loss': total_gain_loss,     # Total gain/loss in dollars
        'total_return': total_return, 
        'positions': {
            key:{'current_value': calculate_position_value(portfolio[key]['shares'], portfolio[key]['current_price']), 'gain_loss': 0, 'return_pct': 0} for key in portfolio.keys()}
    }
                                  

In [68]:
analyze_portfolio(portfolio)

{'total_invested': 82400.0,
 'total_current_value': 74927.0,
 'total_gain_loss': -7473.0,
 'total_return': -9.069174757281553,
 'positions': {'AAPL': {'current_value': 8925.0,
   'gain_loss': 0,
   'return_pct': 0},
  'MSFT': {'current_value': 9307.5, 'gain_loss': 0, 'return_pct': 0},
  'GOOGL': {'current_value': 53015.0, 'gain_loss': 0, 'return_pct': 0},
  'TSLA': {'current_value': 3679.5, 'gain_loss': 0, 'return_pct': 0}}}

In [ ]:
portfolio = {
    'AAPL': {'shares': 50, 'purchase_price': 150.00, 'current_price': 178.50},
    'MSFT': {'shares': 30, 'purchase_price': 280.00, 'current_price': 310.25},
    'GOOGL': {'shares': 20, 'purchase_price': 2800.00, 'current_price': 2650.75},
    'TSLA': {'shares': 15, 'purchase_price': 700.00, 'current_price': 245.30}
}

In [43]:
def analyze_portfolio(portfolio: dict):
    total_invested = 0
    total_current_value = 0
    positions_analysis = {}

    for ticker, data in portfolio.items():
        shares = data['shares']
        purchase_price = data['purchase_price']
        current_price = data['current_price']

        # Calculate metrics for this position
        current_value = calculate_position_value(shares, current_price) //50, 178.50
        gain_loss = calculate_position_gain_loss(shares, purchase_price, current_price)
        return_pct = calculate_position_return(shares, purchase_price, current_price)

        # Store position analysis
        positions_analysis[ticker] = {
            'current_value': current_value,
            'gain_loss': gain_loss,
            'return_pct': return_pct
        }

        # Update Portfolio Totals
        total_invested += calculate_position_cost(shares, purchase_price)
        total_current_value += current_value

    # Calculate overall portfolio metrics
    total_gain_loss = total_current_value - total_invested
    total_return = (total_gain_loss / total_invested) * 100 if total_invested > 0 else 0

    return {
        'total_invested': total_invested,
        'total_current_value': total_current_value,
        'total_gain_loss': total_gain_loss,
        'total_return': total_return,
        'positions': positions_analysis
    }

analyze_portfolio(portfolio)

{'total_invested': 82400.0,
 'total_current_value': 74927.0,
 'total_gain_loss': -7473.0,
 'total_return': -9.069174757281553,
 'positions': {'AAPL': {'current_value': 8925.0,
   'gain_loss': 1425.0,
   'return_pct': 19.0},
  'MSFT': {'current_value': 9307.5,
   'gain_loss': 907.5,
   'return_pct': 10.803571428571429},
  'GOOGL': {'current_value': 53015.0,
   'gain_loss': -2985.0,
   'return_pct': -5.330357142857143},
  'TSLA': {'current_value': 3679.5,
   'gain_loss': -6820.5,
   'return_pct': -64.95714285714286}}}

### Task 3: Formatting Function

**`format_currency(amount)`**
- Parameter: amount (float)
- Returns: formatted string (e.g., "$1,234.56" or "-$567.89")
- Should handle both positive and negative values
- Hint: Use f-strings

### Task 4: Report Generation Function

**`generate_portfolio_report(portfolio)`**
- Parameter: portfolio dictionary
- Returns: None (prints the report)
- This function should:
  1. Call `analyze_portfolio()` to get the analysis
  2. Call `format_currency()` multiple times to format all monetary values
  3. Print a well-formatted report

Expected output format:
```
=== Portfolio Report ===

Individual Positions:
AAPL: Current Value: $8,925.00 | Gain/Loss: $1,425.00 | Return: 28.50%
MSFT: Current Value: $9,307.50 | Gain/Loss: $907.50 | Return: 10.80%
GOOGL: Current Value: $53,015.00 | Gain/Loss: -$2,985.00 | Return: -5.33%
TSLA: Current Value: $3,679.50 | Gain/Loss: -$6,820.50 | Return: -64.99%

Portfolio Summary:
Total Invested: $75,000.00
Current Value: $74,927.00
Total Gain/Loss: -$73.00
Total Return: -0.10%
```

## Testing Your Solution

Test your implementation with the provided portfolio dictionary. Your `generate_portfolio_report(portfolio)` should produce output similar to the example above.

## Bonus Challenge (Optional)

Add a function `find_best_performer(portfolio)` that:
- Analyzes the portfolio
- Returns the stock ticker with the highest percentage return
- Prints: "Best performer: [TICKER] with [X.XX]% return"

## Hints

- Start with the basic calculation functions before moving to more complex ones
- Test each function individually before combining them
- Remember: functions calling other functions make your code more modular and reusable
- Pay attention to the order in which you define your functions